# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rwang <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/13 23:36:24 by rwang             #+#    #+#              #
#    Updated: 2017/07/13 23:38:24 by rwang            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_last

OBJ = last.o

SRC = last.c

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean all
